# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /openwrt/ubox

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /openwrt/ubox

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /openwrt/ubox/CMakeFiles /openwrt/ubox/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /openwrt/ubox/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named board

# Build rule for target.
board: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 board
.PHONY : board

# fast build rule for target.
board/fast:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/build
.PHONY : board/fast

#=============================================================================
# Target rules for targets named kmodloader

# Build rule for target.
kmodloader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kmodloader
.PHONY : kmodloader

# fast build rule for target.
kmodloader/fast:
	$(MAKE) -f CMakeFiles/kmodloader.dir/build.make CMakeFiles/kmodloader.dir/build
.PHONY : kmodloader/fast

#=============================================================================
# Target rules for targets named lsbloader

# Build rule for target.
lsbloader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsbloader
.PHONY : lsbloader

# fast build rule for target.
lsbloader/fast:
	$(MAKE) -f CMakeFiles/lsbloader.dir/build.make CMakeFiles/lsbloader.dir/build
.PHONY : lsbloader/fast

#=============================================================================
# Target rules for targets named mount_root

# Build rule for target.
mount_root: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mount_root
.PHONY : mount_root

# fast build rule for target.
mount_root/fast:
	$(MAKE) -f CMakeFiles/mount_root.dir/build.make CMakeFiles/mount_root.dir/build
.PHONY : mount_root/fast

board.o: board.c.o
.PHONY : board.o

# target to build an object file
board.c.o:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/board.c.o
.PHONY : board.c.o

board.i: board.c.i
.PHONY : board.i

# target to preprocess a source file
board.c.i:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/board.c.i
.PHONY : board.c.i

board.s: board.c.s
.PHONY : board.s

# target to generate assembly for a file
board.c.s:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/board.c.s
.PHONY : board.c.s

kmodloader.o: kmodloader.c.o
.PHONY : kmodloader.o

# target to build an object file
kmodloader.c.o:
	$(MAKE) -f CMakeFiles/kmodloader.dir/build.make CMakeFiles/kmodloader.dir/kmodloader.c.o
.PHONY : kmodloader.c.o

kmodloader.i: kmodloader.c.i
.PHONY : kmodloader.i

# target to preprocess a source file
kmodloader.c.i:
	$(MAKE) -f CMakeFiles/kmodloader.dir/build.make CMakeFiles/kmodloader.dir/kmodloader.c.i
.PHONY : kmodloader.c.i

kmodloader.s: kmodloader.c.s
.PHONY : kmodloader.s

# target to generate assembly for a file
kmodloader.c.s:
	$(MAKE) -f CMakeFiles/kmodloader.dir/build.make CMakeFiles/kmodloader.dir/kmodloader.c.s
.PHONY : kmodloader.c.s

lsbloader.o: lsbloader.c.o
.PHONY : lsbloader.o

# target to build an object file
lsbloader.c.o:
	$(MAKE) -f CMakeFiles/lsbloader.dir/build.make CMakeFiles/lsbloader.dir/lsbloader.c.o
.PHONY : lsbloader.c.o

lsbloader.i: lsbloader.c.i
.PHONY : lsbloader.i

# target to preprocess a source file
lsbloader.c.i:
	$(MAKE) -f CMakeFiles/lsbloader.dir/build.make CMakeFiles/lsbloader.dir/lsbloader.c.i
.PHONY : lsbloader.c.i

lsbloader.s: lsbloader.c.s
.PHONY : lsbloader.s

# target to generate assembly for a file
lsbloader.c.s:
	$(MAKE) -f CMakeFiles/lsbloader.dir/build.make CMakeFiles/lsbloader.dir/lsbloader.c.s
.PHONY : lsbloader.c.s

mount_root.o: mount_root.c.o
.PHONY : mount_root.o

# target to build an object file
mount_root.c.o:
	$(MAKE) -f CMakeFiles/mount_root.dir/build.make CMakeFiles/mount_root.dir/mount_root.c.o
.PHONY : mount_root.c.o

mount_root.i: mount_root.c.i
.PHONY : mount_root.i

# target to preprocess a source file
mount_root.c.i:
	$(MAKE) -f CMakeFiles/mount_root.dir/build.make CMakeFiles/mount_root.dir/mount_root.c.i
.PHONY : mount_root.c.i

mount_root.s: mount_root.c.s
.PHONY : mount_root.s

# target to generate assembly for a file
mount_root.c.s:
	$(MAKE) -f CMakeFiles/mount_root.dir/build.make CMakeFiles/mount_root.dir/mount_root.c.s
.PHONY : mount_root.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... board"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... kmodloader"
	@echo "... list_install_components"
	@echo "... lsbloader"
	@echo "... mount_root"
	@echo "... rebuild_cache"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... kmodloader.o"
	@echo "... kmodloader.i"
	@echo "... kmodloader.s"
	@echo "... lsbloader.o"
	@echo "... lsbloader.i"
	@echo "... lsbloader.s"
	@echo "... mount_root.o"
	@echo "... mount_root.i"
	@echo "... mount_root.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

